"""meso-crct synthetic salience/reward/valuation primitives."""

from .adversarial import ProbeResult, run_reference_probes
from .allocation import (
    AllocationAudit,
    AllocationSample,
    AllocationWindow,
    GoalObligation,
    audit_allocation_window,
    audit_attention_budget,
)
from .allocation_guard import (
    AllocationGuardResult,
    select_with_allocation_guard,
)
from .appraisal import (
    AppraisedTarget,
    TargetAppraisalInput,
    build_target_appraisal,
)
from .arbitration import ArbitrationDecision, ArbitrationMode, arbitrate
from .circuit import CircuitState
from .control import (
    ControlPolicy,
    ControlState,
    ControlStepResult,
    control_step,
)
from .decision_cycle import (
    DecisionCyclePolicy,
    DecisionCycleResult,
    DecisionCycleState,
    RecallMemoryMismatch,
    RecallStateMismatch,
    TargetRecallBinding,
    TargetRecallResolution,
    run_decision_cycle,
)
from .dynamics import DynamicsConfig, advance_without_input, decay_toward
from .episode import (
    ExperienceLearningSpec,
    ExperienceTransactionResult,
    process_appraised_experience,
)
from .events import EventIdentity, EventSequencer
from .evaluation_env import (
    EvalAction,
    EvalStep,
    ProxyTrapEnvironment,
    SensitizationReport,
    TrajectoryAudit,
    audit_trajectory,
    derive_epistemic_value,
    detect_incentive_hedonic_divergence,
)
from .homeostasis import (
    HomeostaticModulation,
    HomeostaticState,
    NeedAffordance,
    NeedAxis,
    modulate_incentive_salience,
)
from .intent import (
    IntentKind,
    IntentPolicy,
    IntentProposal,
    propose_action_intent,
)
from .memory import (
    AssociationIntegrityError,
    AssociationMemory,
    AssociationNotFound,
    AssociationRevision,
    MemoryVersionConflict,
    PlasticityNoOpError,
    PlasticityReplayError,
    apply_candidate,
    quarantine_association,
    register_review_evidence,
    release_association,
    revert_last,
)
from .plasticity import (
    PlasticityCandidate,
    PlasticityPolicy,
    PlasticityReceiptMismatch,
    preview_association_strength,
    propose_plasticity,
)
from .provenance import (
    Provenance,
    ProvenanceVerificationError,
    ProvenanceVerifier,
    SourceKind,
    TransitionReceipt,
    VerifiedProvenance,
    state_fingerprint,
)
from .recall import (
    RecallDirection,
    RecallInfluence,
    RecallLedger,
    RecallReplayError,
    apply_recall_motivation,
    recall_association,
)
from .recall_resolution import (
    RecallDisposition,
    RecallEventMismatch,
    RecallResolution,
    RecallResolutionPolicy,
    resolve_recall_influences,
)
from .review import (
    AssociationQuarantinedError,
    AssociationReviewRecord,
    AssociationReviewRegistry,
    AssociationReviewStaleError,
    ReviewAdmission,
    ReviewDisposition,
    ReviewAssessmentInsufficient,
    ReviewAssessmentMismatch,
    ReviewIntegrityError,
    ReviewNoOpError,
)
from .review_action import (
    ReviewActionKind,
    ReviewActionProposal,
    ReviewActionStaleError,
    propose_review_action,
    validate_review_action_proposal,
)
from .review_evidence import (
    ReviewEvidence,
    ReviewEvidenceAssessment,
    ReviewEvidenceKind,
    ReviewEvidenceConflictError,
    ReviewEvidenceLedger,
    ReviewEvidenceMismatch,
    ReviewEvidenceNotRegistered,
    ReviewEvidenceOutcome,
    ReviewEvidenceReplayError,
    ReviewEvidencePolicy,
    ReviewRiskClass,
    assess_review_evidence,
    bind_review_evidence,
)
from .recruitment import RecruitmentPolicy, RecruitmentTransition, advance_recruitment
from .runtime import (
    RuntimeFrame,
    RuntimePhase,
    classify_phase,
    evaluate_transition,
    frame,
)
from .salience import LearningState, RecruitmentState, SalienceState, SignalKind
from .selection import (
    SelectionPolicy,
    SelectionResult,
    TargetEvaluation,
    TargetState,
    select_target,
)
from .semantic import SemanticAssessment, SemanticEvidence, assess_semantic_relevance
from .tendency import (
    ActionTendency,
    ActionTendencyKind,
    ActionTendencyPolicy,
    derive_action_tendency,
)
from .state import (
    BASELINE_PLEASURE,
    MAX_PLEASURE,
    MIN_PLEASURE,
    RewardState,
    clamp_pleasure,
)

__all__ = [
    "BASELINE_PLEASURE",
    "MAX_PLEASURE",
    "MIN_PLEASURE",
    "RewardState",
    "clamp_pleasure",
    "SignalKind",
    "SalienceState",
    "LearningState",
    "RecruitmentState",
    "RecruitmentPolicy",
    "RecruitmentTransition",
    "advance_recruitment",
    "CircuitState",
    "ControlPolicy",
    "ControlState",
    "ControlStepResult",
    "control_step",
    "DecisionCyclePolicy",
    "DecisionCycleResult",
    "DecisionCycleState",
    "RecallMemoryMismatch",
    "RecallStateMismatch",
    "TargetRecallBinding",
    "TargetRecallResolution",
    "run_decision_cycle",
    "ExperienceLearningSpec",
    "ExperienceTransactionResult",
    "process_appraised_experience",
    "EventIdentity",
    "EventSequencer",
    "DynamicsConfig",
    "decay_toward",
    "advance_without_input",
    "NeedAxis",
    "NeedAffordance",
    "HomeostaticState",
    "HomeostaticModulation",
    "modulate_incentive_salience",
    "IntentKind",
    "IntentPolicy",
    "IntentProposal",
    "propose_action_intent",
    "AssociationRevision",
    "AssociationMemory",
    "AssociationNotFound",
    "AssociationIntegrityError",
    "MemoryVersionConflict",
    "PlasticityNoOpError",
    "PlasticityReplayError",
    "apply_candidate",
    "quarantine_association",
    "register_review_evidence",
    "release_association",
    "revert_last",
    "ReviewDisposition",
    "ReviewAdmission",
    "AssociationReviewRecord",
    "AssociationReviewRegistry",
    "ReviewNoOpError",
    "ReviewIntegrityError",
    "ReviewAssessmentMismatch",
    "ReviewAssessmentInsufficient",
    "ReviewActionKind",
    "ReviewActionProposal",
    "ReviewActionStaleError",
    "propose_review_action",
    "validate_review_action_proposal",
    "ReviewEvidenceKind",
    "ReviewEvidenceOutcome",
    "ReviewEvidencePolicy",
    "ReviewRiskClass",
    "ReviewEvidence",
    "ReviewEvidenceAssessment",
    "ReviewEvidenceMismatch",
    "ReviewEvidenceLedger",
    "ReviewEvidenceReplayError",
    "ReviewEvidenceConflictError",
    "ReviewEvidenceNotRegistered",
    "bind_review_evidence",
    "assess_review_evidence",
    "AssociationQuarantinedError",
    "AssociationReviewStaleError",
    "TargetAppraisalInput",
    "AppraisedTarget",
    "build_target_appraisal",
    "ArbitrationMode",
    "ArbitrationDecision",
    "arbitrate",
    "GoalObligation",
    "AllocationSample",
    "AllocationWindow",
    "AllocationAudit",
    "audit_attention_budget",
    "audit_allocation_window",
    "AllocationGuardResult",
    "select_with_allocation_guard",
    "SourceKind",
    "Provenance",
    "VerifiedProvenance",
    "ProvenanceVerifier",
    "ProvenanceVerificationError",
    "TransitionReceipt",
    "state_fingerprint",
    "RuntimePhase",
    "RuntimeFrame",
    "classify_phase",
    "frame",
    "evaluate_transition",
    "PlasticityPolicy",
    "PlasticityCandidate",
    "PlasticityReceiptMismatch",
    "propose_plasticity",
    "preview_association_strength",
    "RecallDirection",
    "RecallInfluence",
    "RecallLedger",
    "RecallReplayError",
    "recall_association",
    "apply_recall_motivation",
    "RecallDisposition",
    "RecallEventMismatch",
    "RecallResolution",
    "RecallResolutionPolicy",
    "resolve_recall_influences",
    "SelectionPolicy",
    "TargetState",
    "TargetEvaluation",
    "SelectionResult",
    "select_target",
    "ActionTendencyKind",
    "ActionTendencyPolicy",
    "ActionTendency",
    "derive_action_tendency",
    "ProbeResult",
    "run_reference_probes",
    "EvalAction",
    "EvalStep",
    "ProxyTrapEnvironment",
    "TrajectoryAudit",
    "SensitizationReport",
    "audit_trajectory",
    "derive_epistemic_value",
    "detect_incentive_hedonic_divergence",
    "SemanticEvidence",
    "SemanticAssessment",
    "assess_semantic_relevance",
]
